name: Central Workflow Dispatcher .NET 

on:
  workflow_call:
    inputs:
      dotnet:
        description: 'Set this input to force the use of a specific dotnet version.'
        type: string
        required: false
      lint:
        description: 'Run linting on PR. Default true.'
        type: boolean
        default: true
      codecov:
        description: 'Upload coverage report to CodeCov.io. Default true.'
        type: boolean
        default: true
      test-filter:
        description: 'Filter expression for dotnet test (e.g., "Category!=Integration)")'
        type: string
        default: ''
      private:
        type: boolean
        default: false
      lint-auto-fix:
        type: boolean
        default: false
        
jobs:
  build-test:
    if: github.event_name != 'release'
    uses: vivid-orange/Actions/.github/workflows/dotnet-build-test.yml@main
    secrets: inherit
    with:
      lint: ${{ inputs.lint }}
      dotnet: ${{ inputs.dotnet }}
      test-filter: ${{ inputs.test-filter }}
      add-private-nuget: ${{ inputs.private }}
      lint-auto-fix: ${{ inputs.lint-auto-fix }}
      
  codecov-upload:
    needs: build-test
    if: ${{ inputs.codecov == true && github.event_name != 'release' }}
    uses: vivid-orange/Actions/.github/workflows/codecov-upload.yml@main
    secrets: inherit
    with:
      private-repo: ${{ inputs.private }}
      
  pack:
    needs: build-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: vivid-orange/Actions/.github/workflows/dotnet-pack-release.yml@main

  push-nuget:
    if: github.event_name == 'release'
    uses: vivid-orange/Actions/.github/workflows/release-push-nuget.yml@main
    secrets: inherit
    with:
      private-repo: ${{ inputs.private }}
